version: '3.8'
services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
    - .:/usr/src/app

  db:
    container_name: postgres
    image: postgres
    ports:
      - '5432:${DB_PORT}'
    volumes:
      - data:/data/db
      # copy the sql script to create tables
      - ./db/create-tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      # copy the sql script to seed tables
      - ./db/seed-tables.sql:/docker-entrypoint-initdb.d/seed_tables.sql
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

volumes: 
 data: {}
